# Generated by Django 4.1.2 on 2022-12-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artitem',
            name='popularity',
            field=models.FloatField(default=0),
        ),
    ]
