# Generated by Django 4.1.2 on 2022-12-20 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artitem',
            name='minimum_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artitem',
            name='saleStatus',
            field=models.CharField(choices=[('NS', 'Not For Sale'), ('FS', 'For Sale'), ('SO', 'Sold')], default='NS', max_length=2),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('artitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artitem')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
