# Generated by Django 4.1.2 on 2022-11-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='artitem',
            name='artitem_path',
            field=models.TextField(default='artitem/defaultart.jpg'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_path',
            field=models.TextField(default='avatar/default.png'),
        ),
    ]
