# Generated by Django 4.1.2 on 2022-12-23 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_artitem_popularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('user', models.OneToOneField(help_text='User (Required).', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('AR', models.IntegerField(default=0)),
                ('SC', models.IntegerField(default=0)),
                ('SK', models.IntegerField(default=0)),
                ('DR', models.IntegerField(default=0)),
                ('PT', models.IntegerField(default=0)),
                ('PH', models.IntegerField(default=0)),
                ('PR', models.IntegerField(default=0)),
                ('PA', models.IntegerField(default=0)),
                ('PO', models.IntegerField(default=0)),
                ('PW', models.IntegerField(default=0)),
                ('PD', models.IntegerField(default=0)),
                ('PM', models.IntegerField(default=0)),
                ('PG', models.IntegerField(default=0)),
                ('PP', models.IntegerField(default=0)),
                ('PE', models.IntegerField(default=0)),
                ('PF', models.IntegerField(default=0)),
                ('PS', models.IntegerField(default=0)),
                ('OP', models.IntegerField(default=0)),
                ('OT', models.IntegerField(default=0)),
                ('first', models.CharField(choices=[('AR', 'Architecture'), ('SC', 'Sculpture'), ('SK', 'Sketch'), ('DR', 'Drawing'), ('PT', 'Poster'), ('PH', 'Photography'), ('PR', 'Prints'), ('PA', 'Painting/Acrylic'), ('PO', 'Painting Oilpaint'), ('PW', 'Painting Watercolour'), ('PD', 'Painting Digital'), ('PM', 'Painting Mural'), ('PG', 'Painting Gouache'), ('PP', 'Painting Pastel'), ('PE', 'Painting Encaustic'), ('PF', 'Painting Fresco'), ('PS', 'Painting Spray'), ('OP', 'Painting Other'), ('OT', 'Other')], default='OT', max_length=2)),
                ('second', models.CharField(choices=[('AR', 'Architecture'), ('SC', 'Sculpture'), ('SK', 'Sketch'), ('DR', 'Drawing'), ('PT', 'Poster'), ('PH', 'Photography'), ('PR', 'Prints'), ('PA', 'Painting/Acrylic'), ('PO', 'Painting Oilpaint'), ('PW', 'Painting Watercolour'), ('PD', 'Painting Digital'), ('PM', 'Painting Mural'), ('PG', 'Painting Gouache'), ('PP', 'Painting Pastel'), ('PE', 'Painting Encaustic'), ('PF', 'Painting Fresco'), ('PS', 'Painting Spray'), ('OP', 'Painting Other'), ('OT', 'Other')], default='OT', max_length=2)),
                ('third', models.CharField(choices=[('AR', 'Architecture'), ('SC', 'Sculpture'), ('SK', 'Sketch'), ('DR', 'Drawing'), ('PT', 'Poster'), ('PH', 'Photography'), ('PR', 'Prints'), ('PA', 'Painting/Acrylic'), ('PO', 'Painting Oilpaint'), ('PW', 'Painting Watercolour'), ('PD', 'Painting Digital'), ('PM', 'Painting Mural'), ('PG', 'Painting Gouache'), ('PP', 'Painting Pastel'), ('PE', 'Painting Encaustic'), ('PF', 'Painting Fresco'), ('PS', 'Painting Spray'), ('OP', 'Painting Other'), ('OT', 'Other')], default='OT', max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='artitem',
            options={'ordering': ['popularity']},
        ),
    ]
