# Generated by Django 4.1.2 on 2022-10-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_professor_delete_student_delete_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active_user',
            new_name='is_level2',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
