# Generated by Django 4.1.2 on 2022-12-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artitem',
            old_name='saleStatus',
            new_name='sale_status',
        ),
    ]
