# Generated by Django 4.1.2 on 2022-12-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userinterest_alter_artitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artitem',
            options={'ordering': ['-popularity']},
        ),
        migrations.AddField(
            model_name='offlineexhibition',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offlineexhibition',
            name='popularity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='virtualexhibition',
            name='number_of_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='virtualexhibition',
            name='popularity',
            field=models.FloatField(default=0),
        ),
    ]
