# Generated by Django 4.1.2 on 2022-11-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_location_user_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
    ]
