# Generated by Django 4.1.2 on 2022-12-21 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_artitem_bought_by_alter_bid_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artitem',
            name='bought_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_art', to=settings.AUTH_USER_MODEL),
        ),
    ]
