# Generated by Django 4.1.2 on 2022-12-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_artitem_bought_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_bid_flag',
            field=models.BooleanField(default=False),
        ),
    ]
