# Generated by Django 4.1.2 on 2022-12-22 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_new_bid_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBids',
            fields=[
                ('user', models.OneToOneField(help_text='User (Required).', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('new_bids', models.ManyToManyField(blank=True, null=True, to='api.artitem')),
            ],
        ),
    ]
