# Generated by Django 4.1.2 on 2022-12-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_newbids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newbids',
            options={'verbose_name_plural': 'NewBids'},
        ),
        migrations.AlterField(
            model_name='newbids',
            name='new_bids',
            field=models.ManyToManyField(blank=True, to='api.artitem'),
        ),
    ]
