# Generated by Django 4.0.4 on 2022-05-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artitem',
            name='artitem_image',
            field=models.ImageField(blank=True, null=True, upload_to='artitem/'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
