# Generated by Django 4.0.4 on 2022-05-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_artitem_artitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artitem',
            name='artitem_image',
            field=models.ImageField(blank=True, default='artitem/defaultart.jpg', null=True, upload_to='artitem/'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='avatar/profiledef.png', null=True, upload_to='avatar/'),
        ),
    ]
