# Generated by Django 4.0.4 on 2022-05-11 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_myuser_email_myuser_followers_myuser_followes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='followes',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='type',
        ),
        migrations.AddField(
            model_name='myuser',
            name='followed_users',
            field=models.ManyToManyField(blank=True, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artitem',
            name='comments',
            field=models.ManyToManyField(blank=True, to='api.comment'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
