# Generated by Django 4.0.4 on 2022-05-11 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_myuser_followes_remove_myuser_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artitem',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_on',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.artitem'),
            preserve_default=False,
        ),
    ]
