# Generated by Django 4.0.4 on 2022-05-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_artitem_comments_comment_commented_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(default='products of art related to seas and oceans', max_length=100),
            preserve_default=False,
        ),
    ]
