name: Meeting Notes
description: Create Meeting Notest Issue
title: "Meeting Notes: Week# Meeting#"
labels: [documentation, Effort: Medium, Priority: High]
body:

- type: textarea
  attributes:
    label: To Do
    placeholder: |
      * Take notes during the meeting.
      * Create the [wiki page]().
      * Add links to [Sidebar](https://github.com/bounswe/bounswe2022group8/wiki/_Sidebar/_edit) and [Homepage](https://github.com/bounswe/bounswe2022group8/wiki).
  validations:
    required: true

      
- type: textarea
  attributes:
    label: Deadline
    placeholder: |
      01.01.2022 @23.59
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Additional Information
    description: Any additional info about the issue.
  validations:
    required: false
    
