version: "3.8"
   
services:
  web:
    build: .
    command: python /project/manage.py runserver 0.0.0.0:8000 --settings=backend.settings.production
    volumes:
      - .:/project
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
