# Generated by Django 4.1.2 on 2022-12-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
    ]
