# Generated by Django 4.1.2 on 2022-12-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='art_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='history',
            name='is_art',
            field=models.BooleanField(default=False),
        ),
    ]
