# Generated by Django 4.1.2 on 2022-12-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_history_art_id_history_is_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='exhibition_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='history',
            name='is_exhibition',
            field=models.BooleanField(default=False),
        ),
    ]
