# Generated by Django 4.1.2 on 2022-12-09 18:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.TextField(unique=True)),
                ('format', models.TextField(blank=True)),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=None)),
                ('textDirection', models.TextField(blank=True)),
                ('processingLanguage', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextualBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(default='http://www.w3.org/ns/anno.jsonld')),
                ('url', models.TextField(default='http://34.125.134.88/')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.body', to_field='body')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.target', to_field='target')),
                ('type', models.ForeignKey(default='Annotation', on_delete=django.db.models.deletion.CASCADE, to='api.type', to_field='type')),
            ],
        ),
    ]
