# Generated by Django 4.1.2 on 2022-12-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
